#:schema node_modules/wrangler/config-schema.json
name = "cleanup-job"
main = "src/index.ts"
compatibility_date = "2024-08-21"

# Cron Triggers
# Docs: https://developers.cloudflare.com/workers/platform/triggers/cron-triggers/
# Configuration: https://developers.cloudflare.com/workers/wrangler/configuration/#triggers
[triggers]
crons = ["0 3 * * *"] # 0 3 * * * = run once a day at 3 AM

# Variable bindings. These are arbitrary, plaintext strings (similar to environment variables)
# Docs:
# - https://developers.cloudflare.com/workers/wrangler/configuration/#environment-variables
# Note: Use secrets to store sensitive data.
# - https://developers.cloudflare.com/workers/configuration/secrets/
[vars]
ACCOUNT_ID = "<your-project-account-id>"
